apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-hello-kubernetes
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: hello-kubernetes-app
          image: wesyao/hello-kubernetes-app
          ports:
           - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-hello-kubernetes
spec:
  selector:
    # Must match pod label
    app: hello-kubernetes
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
